# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 The Pybricks Authors

PBIO_PLATFORM = cplus_hub
PB_MCU_SERIES = L4
PB_CMSIS_MCU = STM32L431xx
PB_FIRMWARE_MAX_SIZE = 225280
PB_USE_HAL = 1
PB_LIB_BLE5STACK = 1
PB_USE_LSM6DS3TR_C = 1

include ../stm32/stm32.mk
