# SPDX-License-Identifier: MIT
# Copyright (c) 2019 David Lechner

PBIO_PLATFORM = cplus_hub
PB_MCU_SERIES = L4
PB_CMSIS_MCU = STM32L431xx
PB_FIRMWARE_MAX_SIZE = 225280
PB_USE_HAL = 1
PB_LIB_BLE5STACK = 1

include ../stm32.mk
