

#ifndef _PBDRVCONFIG_H_
#define _PBDRVCONFIG_H_

// platform-specific configuration for LEGO BOOST Move Hub

#define PBDRV_CONFIG_HAS_PORT_A (1)
#define PBDRV_CONFIG_HAS_PORT_B (1)
#define PBDRV_CONFIG_HAS_PORT_C (1)
#define PBDRV_CONFIG_HAS_PORT_D (1)

#define PBDRV_CONFIG_FIRST_MOTOR_PORT PBIO_PORT_A
#define PBDRV_CONFIG_LAST_MOTOR_PORT PBIO_PORT_D
#define PBDRV_CONFIG_NUM_MOTOR_CONTROLLER (4)

#endif // _PBDRVCONFIG_H_
