# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 The Pybricks Authors

PBIO_PLATFORM = move_hub
PB_MCU_SERIES = F0
PB_CMSIS_MCU = STM32F070xB
PB_MCU_EXT_OSC_HZ = 0 # uses internal oscillator
PB_FIRMWARE_MAX_SIZE = 108544
PB_LIB_BLUENRG = 1

include ../stm32/stm32.mk
