# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 The Pybricks Authors

PBIO_PLATFORM = move_hub
PB_MCU_SERIES = F0
PB_CMSIS_MCU = STM32F070xB
PB_MCU_EXT_OSC_HZ = 0 # uses internal oscillator
PB_USE_HAL = 1
PB_LIB_BLUENRG = 1
PB_FW_ZIP_INCLUDE_MAIN_MPY = 1

include ../common_stm32/make.mk
