# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 The Pybricks Authors

PBIO_PLATFORM = move_hub
PB_MCU_FAMILY = STM32
PB_MCU_SERIES = F0
PB_CMSIS_MCU = STM32F070xB
PB_MCU_EXT_OSC_HZ = 0 # uses internal oscillator
PB_LIB_STM32_HAL = 1
PB_LIB_BLUENRG = 1
PB_FROZEN_MODULES = 0
MICROPY_ROM_TEXT_COMPRESSION = 0 # Needed for PYBRICKS_OPT_TERSE_ERR

include ../_common/arm_none_eabi.mk
