# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 The Pybricks Authors

DEBUG ?= 1

PBIO_PLATFORM = debug
PB_MCU_SERIES = F4
PB_CMSIS_MCU = STM32F446xx
PB_USE_HAL = 1
PB_FIRMWARE_MAX_SIZE = 524288
TEXT0_ADDR = 0x8000000

include ../stm32/stm32.mk
