# SPDX-License-Identifier: MIT
# Copyright (c) 2019 David Lechner

DEBUG ?= 1

PBIO_PLATFORM = debug
MCU_SERIES = F4
CMSIS_MCU = STM32F446xx
USE_HAL = 1
FIRMWARE_MAX_SIZE = 524288
TEXT0_ADDR = 0x8000000

include ../stm32.mk
