from media_ev3dev_c import Font, Image


class SoundFile:
    _BASE_PATH = "/usr/share/sounds/ev3dev/"

    CAT_PURR = _BASE_PATH + "animals/cat_purr.wav"
    DOG_BARK_1 = _BASE_PATH + "animals/dog_bark_1.wav"
    DOG_BARK_2 = _BASE_PATH + "animals/dog_bark_2.wav"
    DOG_GROWL = _BASE_PATH + "animals/dog_growl.wav"
    DOG_SNIFF = _BASE_PATH + "animals/dog_sniff.wav"
    DOG_WHINE = _BASE_PATH + "animals/dog_whine.wav"
    ELEPHANT_CALL = _BASE_PATH + "animals/elephant_call.wav"
    INSECT_BUZZ_1 = _BASE_PATH + "animals/insect_buzz_1.wav"
    INSECT_BUZZ_2 = _BASE_PATH + "animals/insect_buzz_2.wav"
    INSECT_CHIRP = _BASE_PATH + "animals/insect_chirp.wav"
    SNAKE_HISS = _BASE_PATH + "animals/snake_hiss.wav"
    SNAKE_RATTLE = _BASE_PATH + "animals/snake_rattle.wav"
    T_REX_ROAR = _BASE_PATH + "animals/t-rex_roar.wav"

    BLACK = _BASE_PATH + "colors/black.wav"
    BLUE = _BASE_PATH + "colors/blue.wav"
    BROWN = _BASE_PATH + "colors/brown.wav"
    GREEN = _BASE_PATH + "colors/green.wav"
    RED = _BASE_PATH + "colors/red.wav"
    WHITE = _BASE_PATH + "colors/white.wav"
    YELLOW = _BASE_PATH + "colors/yellow.wav"

    BRAVO = _BASE_PATH + "communication/bravo.wav"
    EV3 = _BASE_PATH + "communication/ev3.wav"
    FANTASTIC = _BASE_PATH + "communication/fantastic.wav"
    GAME_OVER = _BASE_PATH + "communication/game_over.wav"
    GO = _BASE_PATH + "communication/go.wav"
    GOOD = _BASE_PATH + "communication/good.wav"
    GOOD_JOB = _BASE_PATH + "communication/good_job.wav"
    GOODBYE = _BASE_PATH + "communication/goodbye.wav"
    HELLO = _BASE_PATH + "communication/hello.wav"
    HI = _BASE_PATH + "communication/hi.wav"
    LEGO = _BASE_PATH + "communication/lego.wav"
    MINDSTORMS = _BASE_PATH + "communication/mindstorms.wav"
    MORNING = _BASE_PATH + "communication/morning.wav"
    NO = _BASE_PATH + "communication/no.wav"
    OKAY = _BASE_PATH + "communication/okay.wav"
    OKEY_DOKEY = _BASE_PATH + "communication/okey-dokey.wav"
    SORRY = _BASE_PATH + "communication/sorry.wav"
    THANK_YOU = _BASE_PATH + "communication/thank_you.wav"
    YES = _BASE_PATH + "communication/yes.wav"

    BOING = _BASE_PATH + "expressions/boing.wav"
    BOO = _BASE_PATH + "expressions/boo.wav"
    CHEERING = _BASE_PATH + "expressions/cheering.wav"
    CRUNCHING = _BASE_PATH + "expressions/crunching.wav"
    CRYING = _BASE_PATH + "expressions/crying.wav"
    FANFARE = _BASE_PATH + "expressions/fanfare.wav"
    KUNG_FU = _BASE_PATH + "expressions/kung_fu.wav"
    LAUGHING_1 = _BASE_PATH + "expressions/laughing_1.wav"
    LAUGHING_2 = _BASE_PATH + "expressions/laughing_2.wav"
    MAGIC_WAND = _BASE_PATH + "expressions/magic_wand.wav"
    OUCH = _BASE_PATH + "expressions/ouch.wav"
    SHOUTING = _BASE_PATH + "expressions/shouting.wav"
    SMACK = _BASE_PATH + "expressions/smack.wav"
    SNEEZING = _BASE_PATH + "expressions/sneezing.wav"
    SNORING = _BASE_PATH + "expressions/snoring.wav"
    UH_OH = _BASE_PATH + "expressions/uh-oh.wav"

    ACTIVATE = _BASE_PATH + "information/activate.wav"
    ANALYZE = _BASE_PATH + "information/analyze.wav"
    BACKWARDS = _BASE_PATH + "information/backwards.wav"
    COLOR = _BASE_PATH + "information/color.wav"
    DETECTED = _BASE_PATH + "information/detected.wav"
    DOWN = _BASE_PATH + "information/down.wav"
    ERROR = _BASE_PATH + "information/error.wav"
    ERROR_ALARM = _BASE_PATH + "information/error_alarm.wav"
    FLASHING = _BASE_PATH + "information/flashing.wav"
    FORWARD = _BASE_PATH + "information/forward.wav"
    LEFT = _BASE_PATH + "information/left.wav"
    OBJECT = _BASE_PATH + "information/object.wav"
    RIGHT = _BASE_PATH + "information/right.wav"
    SEARCHING = _BASE_PATH + "information/searching.wav"
    START = _BASE_PATH + "information/start.wav"
    STOP = _BASE_PATH + "information/stop.wav"
    TOUCH = _BASE_PATH + "information/touch.wav"
    TURN = _BASE_PATH + "information/turn.wav"
    UP = _BASE_PATH + "information/up.wav"

    AIR_RELEASE = _BASE_PATH + "mechanical/air_release.wav"
    AIRBRAKE = _BASE_PATH + "mechanical/airbrake.wav"
    BACKING_ALERT = _BASE_PATH + "mechanical/backing_alert.wav"
    HORN_1 = _BASE_PATH + "mechanical/horn_1.wav"
    HORN_2 = _BASE_PATH + "mechanical/horn_2.wav"
    LASER = _BASE_PATH + "mechanical/laser.wav"
    MOTOR_IDLE = _BASE_PATH + "mechanical/motor_idle.wav"
    MOTOR_START = _BASE_PATH + "mechanical/motor_start.wav"
    MOTOR_STOP = _BASE_PATH + "mechanical/motor_stop.wav"
    RATCHET = _BASE_PATH + "mechanical/ratchet.wav"
    SONAR = _BASE_PATH + "mechanical/sonar.wav"
    TICK_TACK = _BASE_PATH + "mechanical/tick_tack.wav"

    SPEED_DOWN = _BASE_PATH + "movements/speed_down.wav"
    SPEED_IDLE = _BASE_PATH + "movements/speed_idle.wav"
    SPEED_UP = _BASE_PATH + "movements/speed_up.wav"

    ZERO = _BASE_PATH + "numbers/zero.wav"
    ONE = _BASE_PATH + "numbers/one.wav"
    TWO = _BASE_PATH + "numbers/two.wav"
    THREE = _BASE_PATH + "numbers/three.wav"
    FOUR = _BASE_PATH + "numbers/four.wav"
    FIVE = _BASE_PATH + "numbers/five.wav"
    SIX = _BASE_PATH + "numbers/six.wav"
    SEVEN = _BASE_PATH + "numbers/seven.wav"
    EIGHT = _BASE_PATH + "numbers/eight.wav"
    NINE = _BASE_PATH + "numbers/nine.wav"
    TEN = _BASE_PATH + "numbers/ten.wav"

    CLICK = _BASE_PATH + "system/click.wav"
    CONFIRM = _BASE_PATH + "system/confirm.wav"
    GENERAL_ALERT = _BASE_PATH + "system/general_alert.wav"
    OVERPOWER = _BASE_PATH + "system/overpower.wav"
    READY = _BASE_PATH + "system/ready.wav"


class ImageFile:
    _BASE_PATH = "/usr/share/images/ev3dev/mono/"

    ANGRY = _BASE_PATH + "eyes/angry.png"
    AWAKE = _BASE_PATH + "eyes/awake.png"
    BLACK_EYE = _BASE_PATH + "eyes/black_eye.png"
    BOTTOM_LEFT = _BASE_PATH + "eyes/bottom_left.png"
    BOTTOM_RIGHT = _BASE_PATH + "eyes/bottom_right.png"
    CRAZY_1 = _BASE_PATH + "eyes/crazy_1.png"
    CRAZY_2 = _BASE_PATH + "eyes/crazy_2.png"
    DISAPPOINTED = _BASE_PATH + "eyes/disappointed.png"
    DIZZY = _BASE_PATH + "eyes/dizzy.png"
    DOWN = _BASE_PATH + "eyes/down.png"
    EVIL = _BASE_PATH + "eyes/evil.png"
    HURT = _BASE_PATH + "eyes/hurt.png"
    KNOCKED_OUT = _BASE_PATH + "eyes/knocked_out.png"
    LOVE = _BASE_PATH + "eyes/love.png"
    MIDDLE_LEFT = _BASE_PATH + "eyes/middle_left.png"
    MIDDLE_RIGHT = _BASE_PATH + "eyes/middle_right.png"
    NEUTRAL = _BASE_PATH + "eyes/neutral.png"
    NUCLEAR = _BASE_PATH + "eyes/nuclear.png"
    PINCHED_LEFT = _BASE_PATH + "eyes/pinched_left.png"
    PINCHED_MIDDLE = _BASE_PATH + "eyes/pinched_middle.png"
    PINCHED_RIGHT = _BASE_PATH + "eyes/pinched_right.png"
    SLEEPING = _BASE_PATH + "eyes/sleeping.png"
    TEAR = _BASE_PATH + "eyes/tear.png"
    TIRED_LEFT = _BASE_PATH + "eyes/tired_left.png"
    TIRED_MIDDLE = _BASE_PATH + "eyes/tired_middle.png"
    TIRED_RIGHT = _BASE_PATH + "eyes/tired_right.png"
    TOXIC = _BASE_PATH + "eyes/toxic.png"
    UP = _BASE_PATH + "eyes/up.png"
    WINKING = _BASE_PATH + "eyes/winking.png"

    ACCEPT = _BASE_PATH + "information/accept.png"
    BACKWARD = _BASE_PATH + "information/backward.png"
    DECLINE = _BASE_PATH + "information/decline.png"
    FORWARD = _BASE_PATH + "information/forward.png"
    LEFT = _BASE_PATH + "information/left.png"
    NO_GO = _BASE_PATH + "information/no_go.png"
    QUESTION_MARK = _BASE_PATH + "information/question_mark.png"
    RIGHT = _BASE_PATH + "information/right.png"
    STOP_1 = _BASE_PATH + "information/stop_1.png"
    STOP_2 = _BASE_PATH + "information/stop_2.png"
    THUMBS_DOWN = _BASE_PATH + "information/thumbs_down.png"
    THUMBS_UP = _BASE_PATH + "information/thumbs_up.png"
    WARNING = _BASE_PATH + "information/warning.png"

    EV3 = _BASE_PATH + "lego/ev3.png"
    EV3_ICON = _BASE_PATH + "lego/ev3_icon.png"

    TARGET = _BASE_PATH + "objects/target.png"
