// SPDX-License-Identifier: MIT
// Copyright (c) 2020-2023 The Pybricks Authors

#define PBSYS_CONFIG_FEATURE_BUILTIN_USER_PROGRAM_REPL             (0)
#define PBSYS_CONFIG_FEATURE_BUILTIN_USER_PROGRAM_PORT_VIEW        (0)
#define PBSYS_CONFIG_FEATURE_BUILTIN_USER_PROGRAM_IMU_CALIBRATION  (0)
#define PBSYS_CONFIG_FEATURE_PROGRAM_FORMAT_MULTI_MPY_V6           (1)
#define PBSYS_CONFIG_FEATURE_PROGRAM_FORMAT_MULTI_MPY_V6_1_NATIVE  (0)
#define PBSYS_CONFIG_MAIN                           (1)
#define PBSYS_CONFIG_STORAGE                        (1)
#define PBSYS_CONFIG_STORAGE_RAM_SIZE               (10 * 1024)
#define PBSYS_CONFIG_STORAGE_ROM_SIZE               (PBDRV_CONFIG_BLOCK_DEVICE_TEST_SIZE)
#define PBSYS_CONFIG_STORAGE_USER_DATA_SIZE         (512)
#define PBSYS_CONFIG_STATUS_LIGHT                   (0)
#define PBSYS_CONFIG_STATUS_LIGHT_BATTERY           (0)
#define PBSYS_CONFIG_STATUS_LIGHT_BLUETOOTH         (0)
#define PBSYS_CONFIG_USER_PROGRAM                   (1)
#define PBSYS_CONFIG_USER_PROGRAM_AUTO_START        (1)
#define PBSYS_CONFIG_PROGRAM_STOP                   (1)
