#ifndef PBIO_EV3_EXCEPTIONHANDLER_H_
#define PBIO_EV3_EXCEPTIONHANDLER_H_

#define EV3_PANIC_UNKNOWN           0
#define EV3_PANIC_UNDEFINED_INSTR   1
#define EV3_PANIC_PREFETCH_ABORT    2
#define EV3_PANIC_DATA_ABORT        3

#endif // PBIO_EV3_EXCEPTIONHANDLER_H_
