// SPDX-License-Identifier: MIT
// Copyright (c) 2023-2024 The Pybricks Authors

#define PBIO_CONFIG_BATTERY                 (1)
#define PBIO_CONFIG_DCMOTOR                 (1)
#define PBIO_CONFIG_DCMOTOR_NUM_DEV         (4)
#define PBIO_CONFIG_DRIVEBASE_SPIKE         (0)
#define PBIO_CONFIG_IMAGE                   (1)
#define PBIO_CONFIG_IMU                     (0)
#define PBIO_CONFIG_LIGHT                   (1)
#define PBIO_CONFIG_LIGHT_MATRIX            (1)
#define PBIO_CONFIG_LOGGER                  (1)
#define PBIO_CONFIG_MOTOR_PROCESS           (1)
#define PBIO_CONFIG_PORT                    (1)
#define PBIO_CONFIG_PORT_NUM_DEV            (8)
#define PBIO_CONFIG_PORT_DCM                (1)
#define PBIO_CONFIG_PORT_DCM_PUP            (0)
#define PBIO_CONFIG_PORT_DCM_EV3            (1)
#define PBIO_CONFIG_PORT_DCM_NUM_DEV        (4)
#define PBIO_CONFIG_PORT_LUMP               (1)
#define PBIO_CONFIG_PORT_LUMP_MODE_INFO     (1)
#define PBIO_CONFIG_PORT_LUMP_NUM_DEV       (4)
#define PBIO_CONFIG_SERVO                   (1)
#define PBIO_CONFIG_SERVO_NUM_DEV           (4)
#define PBIO_CONFIG_SERVO_EV3_NXT           (1)
#define PBIO_CONFIG_SERVO_PUP               (0)
#define PBIO_CONFIG_SERVO_PUP_MOVE_HUB      (0)
#define PBIO_CONFIG_TACHO                   (1)

#define PBIO_CONFIG_ENABLE_SYS              (1)
