# SPDX-License-Identifier: MIT
# Copyright (c) 2025 The Pybricks Authors

PBIO_PLATFORM = sim_hub
PB_MCU_FAMILY = desktop
PB_FROZEN_MODULES = 1
MICROPY_ROM_TEXT_COMPRESSION = 1


include ../_common/arm_none_eabi.mk
