// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2020 The Pybricks Authors

#ifndef _PBDRVCONFIG_H_
#define _PBDRVCONFIG_H_

#define PBDRV_CONFIG_HUB_PRIMEHUB

#define PBDRV_CONFIG_ADC                            (1)
#define PBDRV_CONFIG_ADC_STM32_HAL                  (1)
#define PBDRV_CONFIG_ADC_STM32_HAL_ADC_INSTANCE     ADC1
#define PBDRV_CONFIG_ADC_STM32_HAL_ADC_NUM_CHANNELS 6
#define PBDRV_CONFIG_ADC_STM32_HAL_DMA_INSTANCE     DMA2_Stream0
#define PBDRV_CONFIG_ADC_STM32_HAL_DMA_CHANNEL      DMA_CHANNEL_0
#define PBDRV_CONFIG_ADC_STM32_HAL_DMA_IRQ          DMA2_Stream0_IRQn
#define PBDRV_CONFIG_ADC_STM32_HAL_TIMER_INSTANCE   TIM2
#define PBDRV_CONFIG_ADC_STM32_HAL_TIMER_TRIGGER    ADC_EXTERNALTRIGCONV_T2_TRGO

#define PBDRV_CONFIG_BATTERY                        (1)
#define PBDRV_CONFIG_BATTERY_ADC                    (1)
#define PBDRV_CONFIG_BATTERY_ADC_VOLTAGE_CH         1
#define PBDRV_CONFIG_BATTERY_ADC_VOLTAGE_RAW_MAX    4095
#define PBDRV_CONFIG_BATTERY_ADC_VOLTAGE_SCALED_MAX 9615
#define PBDRV_CONFIG_BATTERY_ADC_CURRENT_CH         0
#define PBDRV_CONFIG_BATTERY_ADC_CURRENT_RAW_MAX    4095
#define PBDRV_CONFIG_BATTERY_ADC_CURRENT_SCALED_MAX 4175

#define PBDRV_CONFIG_BUTTON                         (1)
#define PBDRV_CONFIG_KEYPAD                         (1)
#define PBDRV_CONFIG_BUTTON_ADC                     (1)

#define PBDRV_CONFIG_COUNTER                        (1)
#define PBDRV_CONFIG_COUNTER_NUM_DEV                (5)
// #define PBDRV_CONFIG_COUNTER_NUM_DEV                (6)

#define PBDRV_CONFIG_GPIO                           (1)
#define PBDRV_CONFIG_GPIO_STM32F4                   (1)

#define PBDRV_CONFIG_IOPORT                         (1)
#define PBDRV_CONFIG_IOPORT_LPF2                    (1)
#define PBDRV_CONFIG_IOPORT_LPF2_NUM_PORTS          (5)
// #define PBDRV_CONFIG_IOPORT_LPF2_NUM_PORTS          (6)
#define PBDRV_CONFIG_IOPORT_LPF2_FIRST_PORT         PBIO_PORT_A
#define PBDRV_CONFIG_IOPORT_LPF2_LAST_PORT          PBIO_PORT_E
// #define PBDRV_CONFIG_IOPORT_LPF2_LAST_PORT          PBIO_PORT_F

#define PBDRV_CONFIG_UART                           (1)
#define PBDRV_CONFIG_UART_STM32_HAL                 (1)

#define PBDRV_CONFIG_USB                            (1)
#define PBDRV_CONFIG_USB_STM32F4_CDC                (1)

#define PBDRV_CONFIG_BLUETOOTH      (0)
#define PBDRV_CONFIG_LIGHT          (0)
#define PBDRV_CONFIG_MOTOR          (1)

#define PBDRV_CONFIG_HAS_PORT_A (1)
#define PBDRV_CONFIG_HAS_PORT_B (1)
#define PBDRV_CONFIG_HAS_PORT_C (1)
#define PBDRV_CONFIG_HAS_PORT_D (1)
#define PBDRV_CONFIG_HAS_PORT_E (1)
// #define PBDRV_CONFIG_HAS_PORT_F (1)

#define PBDRV_CONFIG_FIRST_IO_PORT          PBIO_PORT_A
#define PBDRV_CONFIG_LAST_IO_PORT           PBIO_PORT_E
// #define PBDRV_CONFIG_LAST_IO_PORT           PBIO_PORT_F
#define PBDRV_CONFIG_NUM_IO_PORT            (5)
// #define PBDRV_CONFIG_NUM_IO_PORT            (6)

#define PBDRV_CONFIG_FIRST_MOTOR_PORT       PBIO_PORT_A
#define PBDRV_CONFIG_LAST_MOTOR_PORT        PBIO_PORT_E
// #define PBDRV_CONFIG_LAST_MOTOR_PORT        PBIO_PORT_F
#define PBDRV_CONFIG_NUM_MOTOR_CONTROLLER   (5)
// #define PBDRV_CONFIG_NUM_MOTOR_CONTROLLER   (6)

#define PBDRV_CONFIG_SYS_CLOCK_RATE 96000000

#endif // _PBDRVCONFIG_H_
