test_all_1
(0, 1)
0 0
<class 'StopIteration'> ()
<class 'StopIteration'> ()
test_all_2
<class 'RuntimeError'> ('task2',)
1 0
<class 'StopIteration'> ()
<class 'StopIteration'> ()
test_race_1
(0, None)
0 1
<class 'StopIteration'> ()
<class 'StopIteration'> ()
test_race_2
<class 'RuntimeError'> ('task2',)
1 0
<class 'StopIteration'> ()
<class 'StopIteration'> ()
test_race_false
(0, 1)
0 0
<class 'StopIteration'> ()
<class 'StopIteration'> ()
