# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 The Pybricks Authors

PBIO_PLATFORM = city_hub
PB_MCU_SERIES = F0
PB_CMSIS_MCU = STM32F030xC
PB_FIRMWARE_MAX_SIZE = 237568
PB_LIB_BLE5STACK = 1

include ../stm32/stm32.mk
